### ISSUE TITLE
Yuya wrong set

### ISSUE THREAD

**Issue by Pigxel** [Mushymato/dl#28]
In the simulator, Yuya is using Sakuya and TB + LC instead of DK rath. For reference, he is a lot better with DK rath (TB + Lurker) instead of Sakuya (TB + LC).
DK rath:
**Yuya 180s** (co-ab: dagger) [Twinfold_Bonds+The_Lurker_in_the_Woods][Dreadking_Rathalos][Agito]```DPS: 8525 <hit15 & hp60>
attack: 2061|force_strike: 4135|skill_1: 2328``````DPS: 6063
attack: 1466|force_strike: 2941|skill_1: 1654```
![image](https://user-images.githubusercontent.com/61822720/75961011-17a9e080-5efc-11ea-9070-0a3383b619a7.png)

the current build on the simulator: 
![Capture](https://user-images.githubusercontent.com/61822720/75960910-f1844080-5efb-11ea-8e5f-385d9e560532.PNG)

**Comment by Mushymato** [comment]
updated
