### ISSUE TITLE
Valerio FSF

### ISSUE THREAD

**Issue by eddoro** [Mushymato/dl#34]
On the sim, Valerio is using Siren + Resounding Rendition + Primal Crisis w/ 12422 DPS. However, it is better to run DY!Jeanne + The Wyrmclan Duo + Primal Crisis and change the `dessert` in the ACL to `entree`.

![12842 dps Valerio](https://snipboard.io/dOjNgv.jpg)

This can be further improved by the fact that Valerio can fsf out of entree c3.
[Gif link](https://i.imgur.com/P32u7j3.gif)

He is able to get all 12 hits on C3 on HBH as well, even though video uses Roy.
Before the clap is the FSF combo, and after the clap is the normal recovery time for comparison. The C3FSF recovery was counted to be around 11/60, and when changing the 66/60 number in his file to this, Valerio's DPS went to 14895 DPS with DY!Jeanne + TWD + PC + 20k team DPS. (1000 runs were done. 25 runs outputted 14920.)

![new valerio](https://snipboard.io/IOWKxf.jpg)

Even if 11/60 is an underestimation, any value between is still a significant DPS gain.

**Comment by Mushymato** [comment]
It looks like vid has +20% atk speed while our frame data needs to be +0% atk speed (so use 14f instead of 11f). I'd also greatly appreciate if you can try fsf on his other stances.

For now I didn't change the frames but did add in `fsf`, which uses the default blade fsf (33f)

**Comment by eddoro** [comment]
Appetizer skips last 3 hits when FSF and dessert stance seems to work, will work on frames tomorrow.

**Comment by eddoro** [comment]
When trying dessert fsf the values matched with the 69f you already had in the code. 
[Video Ref](https://streamable.com/rbfii)

Couldn't get appetizer fsf to work without critting at least once (even with levi+no crit prints) so instead focused on consistently getting aspd and recording with it. It was 55 frames with 20% speed, so around 66f adjusted, but it also skips hits.
[Video Ref](https://streamable.com/yvznh)

**Comment by Mushymato** [comment]
verified in game data that valerio has no special FS for stance, also confirmed that entree c3 is projectile. Will retain standard 33f fsf for him.
