### ISSUE TITLE
About missing wyrmprint...

### ISSUE THREAD

**Issue by Lyamori** [Mushymato/dl#39]
Hello. I'm Japanese user of Dragalia simulator.
First, thank for everything you do. This site is very amazing!

So, Id like to talk to you about a missing wyrmprint in the custom simulator : Wily Warriors: Metal & Quick in the mega man collab.
If you can add it, it would be great! 

Maybe there are reasons for its absence...

Thank you and good luck for the future!

**Comment by Mushymato** [comment]
sim does not handle slayer's strength in a sensible way, so we generally do not add those types of prints.
